# Generated by Django 2.2.9 on 2020-01-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_githubprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
