# Generated by Django 2.2.9 on 2020-01-10 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200104_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(help_text='Authenticated user.', on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
    ]
