# Generated by Django 2.2.9 on 2020-01-12 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200110_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='github_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('sha', 'repository')},
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'full_name')},
        ),
    ]
