# Generated by Django 2.2.9 on 2020-01-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200112_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Repository'),
            preserve_default=False,
        ),
    ]
